# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Parallel < Formula
  desc "Parallel runs multiple commands concurrently, treating them as a group."
  homepage "https://github.com/rosszurowski/parallel"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rosszurowski/parallel/releases/download/0.0.1/parallel_0.0.1_darwin_arm64.tar.gz"
      sha256 "a9aa81ac30d31f6ba370cc046ce6dc0b13038a064ac8c19fc6a2527402f88086"

      def install
        bin.install "parallel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rosszurowski/parallel/releases/download/0.0.1/parallel_0.0.1_darwin_amd64.tar.gz"
      sha256 "0e18c1cb56142fb9e6d832a3f49c1602dd657228a0ac9f2cf830aa883125f139"

      def install
        bin.install "parallel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rosszurowski/parallel/releases/download/0.0.1/parallel_0.0.1_linux_amd64.tar.gz"
      sha256 "65ef5b5efa6c1501c2c5d7a514e136d5bb3672efc8a9f2bb536d8ac7d5c643a4"

      def install
        bin.install "parallel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rosszurowski/parallel/releases/download/0.0.1/parallel_0.0.1_linux_arm64.tar.gz"
      sha256 "82f2829a997f157e32d249c7aa5621ba314692f2fabe1ea85b5cbdf16ee0767b"

      def install
        bin.install "parallel"
      end
    end
  end
end
