# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tandem < Formula
  desc "tandem runs commands in parallel, treating them as a group."
  homepage "https://github.com/rosszurowski/tandem"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rosszurowski/tandem/releases/download/0.0.1/tandem_0.0.1_darwin_amd64.tar.gz"
      sha256 "a95b65f88b697213dfd05bb1b4edc966cb24311feb4007b296b590b98e79dba4"

      def install
        bin.install "tandem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rosszurowski/tandem/releases/download/0.0.1/tandem_0.0.1_darwin_arm64.tar.gz"
      sha256 "74cdff139b3dc0dc288469a6122dae1359b46502988b57a0eb00fb919a035cff"

      def install
        bin.install "tandem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rosszurowski/tandem/releases/download/0.0.1/tandem_0.0.1_linux_arm64.tar.gz"
      sha256 "f701f6af70b75e037dca8d8308ddc4c301fa5cd570c17adfe57a2b1c479e31d9"

      def install
        bin.install "tandem"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rosszurowski/tandem/releases/download/0.0.1/tandem_0.0.1_linux_amd64.tar.gz"
      sha256 "fcee1b1af89ad8b8b38a8d84fe2935c71ec08de4f9cdaf6dd0f4249f2fed5b5f"

      def install
        bin.install "tandem"
      end
    end
  end
end
