# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tandem < Formula
  desc "tandem runs commands in parallel, treating them as a group."
  homepage "https://github.com/rosszurowski/tandem"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rosszurowski/tandem/releases/download/0.0.3/tandem_0.0.3_darwin_amd64.tar.gz"
      sha256 "62f88b82bf6a529da7e352c2b887913bd87dea1240b3e9fa177729bf3dd5ba77"

      def install
        bin.install "tandem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rosszurowski/tandem/releases/download/0.0.3/tandem_0.0.3_darwin_arm64.tar.gz"
      sha256 "8c4a230100292f2b9e4bb77915b1dc604e786499757526904189fb14253ec097"

      def install
        bin.install "tandem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rosszurowski/tandem/releases/download/0.0.3/tandem_0.0.3_linux_arm64.tar.gz"
      sha256 "dab2cc66aaf7af8c483d65801ed3a0627eb1da493738c6fb132d62b6a352c58c"

      def install
        bin.install "tandem"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rosszurowski/tandem/releases/download/0.0.3/tandem_0.0.3_linux_amd64.tar.gz"
      sha256 "bda5347e5388ad8215d10b7abe0394fa9c4214080c10631c88bab05ec0f98689"

      def install
        bin.install "tandem"
      end
    end
  end
end
